  query placesByName($name: String!) {
   
     cmsData: places(where: { Name: $name }) {
      id
      identifier: Identifier
      name: Name
      description : Description
    }

    }





   
  